name: Cypress Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Start the app preview server
        run: npm run preview &

      - name: Wait for the server
        run: npx wait-on http://localhost:4173

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless
