name: Cypress E2E Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Cypress binary
        id: cypress-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Cypress (only if not cached)
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Start server and run Cypress tests
        run: |
          npm run preview &
          npx wait-on http://localhost:4173
          npm run cypress:run
        env:
          CYPRESS_baseUrl: http://localhost:4173

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos 