name: Cypress Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Cypress deps
        id: cypress-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build

      - name: Install Cypress (only if not cached)
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Start server and run Cypress tests
        run: |
          npm run preview &
          npx wait-on http://localhost:4173
        env:
          CYPRESS_baseUrl: http://localhost:4173

      - run: npm run cypress:run
