name: E2E Tests (Cypress)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Start the server
        run: npm run preview &
      
      - name: Wait for the server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: false
          wait-on: 'http://localhost:5173'
          browser: chrome
          headless: true
